name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - jupyterlab
  - seaborn
  - pandas==1.2.4
  - pip=20.3.3
  - pandas-profiling
  - pyarrow
  - pip:
      - wandb==0.10.21
      - protobuf==3.20.*