name: nyc_airbnb_dev
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - mlflow==1.2.0
  - ipython
  - notebook
  - jupyterlab
  - cookiecutter
  - hydra-core
  - matplotlib==3.4.1
  - pandas==1.2.4
  - git==2.34.1
  - pip=20.3.3
  - pip:
      - wandb==0.10.21
      - protobuf==3.20.*
