name: train_random_forest
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pandas==1.2.4
  - pip=20.3.3
  - mlflow==1.2.0
  - scikit-learn=0.24.1
  - matplotlib
  - pillow
  - pip:
      - wandb==0.10.31
      - protobuf==3.20.*
